### ISSUE TITLE
Make header more dynamic

### ISSUE THREAD

**Issue by rayhagimoto** [rayhagimoto/resume#1]
Currently \MakeHeader is hardcoded using

```latex
%----------------------------------------------------------
% Strip "<scheme>://" from URL for display
%----------------------------------------------------------
\newcommand{\ShortURL}[1]{%
  \IfSubStr{#1}{://}{%
    \StrBehind{#1}{://}[\urlbody]%
    \urlbody
  }{#1}%
}

%----------------------------------------------------------
% === PERSONAL INFO MACROS ===
%----------------------------------------------------------
\newcommand{\Name}{}
\newcommand{\Title}{}
\newcommand{\Phone}{}
\newcommand{\Email}{}
\newcommand{\Location}{}
\newcommand{\LinkedInURL}{}
\newcommand{\WebsiteURL}{}

%----------------------------------------------------------
% === HEADER MACRO ===
%----------------------------------------------------------
\newcommand{\MakeHeader}{%
  \begin{center}
    {\large\bfseries \MakeUppercase{\Name}}\\
    \vspace{0.2em}
    {\itshape \Title}\\
    \vspace{0.2em}
    \Phone \,$|$\, 
    \href{mailto:\Email}{\Email} \,$|$\, 
    \href{\LinkedInURL}{\ShortURL{\LinkedInURL}} \,$|$\, 
    \href{\WebsiteURL}{\ShortURL{\WebsiteURL}}\\
    \vspace{0.2em}
    Address: \Location
  \end{center}
}
```

But I want the user to be able to specify the order that the content will render, and add additional URLs, with custom formatting. Basically, the order in which the fields show up in the `profile` section should update the order they show up in the header. Currently the GitHub URL doesn't render. 

```
profile:
  name: 'John Doe'
  title: 'Title'
  location: 'Addy'
  phone: '(123) 456-7890'
  email: 'johndoe@gmail.com'
  description: >
    Multiline description goes here.
  website: 'https//johndoe.dev'
  linkedin: 'https://linkedin.com/in/john-doe'
  github: 'https://github.com/johndoe' 
```
